plugins {
    id 'com.android.application'
}

dependencies {
    implementation 'com.android.billingclient:billing:9.1.0'
}

android {
    namespace 'com.arcanum.classic'
    compileSdk 36

    defaultConfig {
        applicationId 'com.arcanum.classic'
        minSdk 26
        targetSdk 36
        versionCode 12
        versionName '1.2.7'
    }

    buildTypes {
        debug {
            debuggable false
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

